spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
#  datasource:
#    url: jdbc:h2:mem:meloddb
#    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        security: DEBUG